### ISSUE TITLE
reset admin password link is redirect to the default user

### ISSUE THREAD

**Issue by Ahmad-Fathy** [SagarMaheshwary/laravel-multiauth#5]
In reset Admin password 
Reset Password link in the mail redirect to the default user reset form not to the admin reset form as expected

**Comment by SagarMaheshwary** [comment]
It's working just fine on my side. Can you please check the url in the email?

**Comment by server102** [comment]
The reset password link in the mail shows /password/reset instead of /admin/password/reset. I guess overriding the **sendPasswordResetNotification** method on the Admin model should fix the problem.

**Comment by SagarMaheshwary** [comment]
It's already done in Admin model:
```php
<?php

use App\Notifications\AdminResetPasswordNotification as Notification;

/**
 * Custom password reset notification.
 * 
 * @return void
 */
public function sendPasswordResetNotification($token)
{
    $this->notify(new Notification($token));
}
