### ISSUE TITLE
Admin Login 

### ISSUE THREAD

**Issue by zarnab87** [SagarMaheshwary/laravel-multiauth#7]
What is the route/URL for the admin login page? I'm unable to open it.
As I'm a newbie, summarize the working flow for the project.

**Comment by zarnab87** [comment]
/admin/login. 404 Not found error occurs.

**Comment by SagarMaheshwary** [comment]
Go to /login for normal users and /admin/login for admin users.

**Comment by zarnab87** [comment]
Swift_TransportException (530)
Expected response code 250 but got code "530", with message "530 5.7.1 Authentication required "

When I'm trying to register a new user, after pressing the button, this error has come. How to resolve it?

**Comment by SagarMaheshwary** [comment]
That's because we are sending a verification email to the new user so you need to add the mail server credentials (e.g mailtrap).

**Comment by zarnab87** [comment]
Symfony \ Component \ HttpKernel \ Exception \ MethodNotAllowedHttpException
The GET method is not supported for this route. Supported methods: POST.

I got this error on /admin/login route.

**Comment by SagarMaheshwary** [comment]
This repo belongs to a tutorial so reading that might help.

**Comment by zarnab87** [comment]
okk
