### ISSUE TITLE
In PackageManifest.php line 122:    Undefined index: name After Composser Install

### ISSUE THREAD

**Issue by edy-kurniawan** [SagarMaheshwary/laravel-multiauth#8]
![Screenshot (45)](https://user-images.githubusercontent.com/33270746/107166555-efb6dd00-69e8-11eb-969c-220fa5cd480a.png)

**Comment by SagarMaheshwary** [comment]
Please tell the composer version installed on your system.

**Comment by edy-kurniawan** [comment]
Composer version 2.0.8 2020-12-03 17:20:38

**Comment by SagarMaheshwary** [comment]
Composer 2 has some new autoloading standards and will have issues with autoloading old packages so you need to downgrade your composer installation.

Run this command in terminal to downgrade: composer self-update --1

Reference: https://stackoverflow.com/a/64598028
